# Generated by Django 3.0 on 2019-12-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ideia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=50)),
                ('Sobrenome', models.CharField(blank=True, max_length=50, null=True)),
                ('Nova_ideia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nova Ideia')),
                ('Descricao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('Viabilidade', models.CharField(choices=[('1-Baixa', '1-Baixa'), ('2-Regular', '2-Regular'), ('3-Média', '3-Média'), ('4-Viável', '4-Viável'), ('5-Alta', '5-Alta')], default=None, max_length=30)),
                ('Situacao', models.CharField(choices=[('Registrada', 'Registrada'), ('Em Desenvolvimento', 'Em Desenvolvimento'), ('Cancelada', 'Cancelada'), ('Desenvolvida', 'Desenvolvida')], default=None, max_length=30, verbose_name='Situação')),
                ('Data', models.DateTimeField()),
            ],
        ),
    ]
